language: java

before_install:
  - sudo wget https://github.com/bell-sw/Liberica/releases/download/11.0.2/bellsoft-jdk11.0.2-linux-amd64.deb
  - sudo apt-get update -q
  - sudo apt-get install ./bellsoft-jdk11.0.2-linux-amd64.deb -y
  - export JAVA_HOME=/usr/lib/jvm/jdk-11-bellsoft-amd64
  - echo $JAVA_HOME

after_failure:
  - cat /home/travis/build/FHNW-IP5-IP6/InheritorGallery/inheritorgallery-core/build/reports/tests/test/index.html

deploy:
  provider: releases
  api_key: e9bef81874bd3bd8491ad08b1b23854b10b79682
  file: README.md
  skip_cleanup: true
  on:
    tags: true
