= Java to UML Parser

Dieses Dokument sammelt mögliche Lösungen um aus .java Files
UML darzustellen.

== Reflection

* Reflection is commonly used by programs which require the ability to examine or modify the runtime behavior
of applications running in the Java virtual machine.
https://docs.oracle.com/javase/tutorial/reflect/
https://www.javatpoint.com/java-reflection

* private fields and methods
http://tutorials.jenkov.com/java-reflection/private-fields-and-methods.html


== Java.lang.Class.getMethods() Method

* Nur public Methoden
https://www.tutorialspoint.com/java/lang/class_getmethods.htm


== Teilweise vorgefertigte Lösungen

* eher unflexibel, weil diverse Tools benötigt werden
https://github.com/rishirajrandive/uml-parser

* Favorit: einfach, mächtig und flexibel
https://github.com/javaparser/javaparser
https://github.com/javaparser/javaparser-maven-sample +
siehe Auch javaparservisited.pdf


* benutzt javaparser und yuml für uml visualisierung
https://github.com/shubhamvadhera/uml-parser

== JavaParser

Javaparser API kann .java Files parser und diese in einer
Baumartiger Struktur speichern. Dabei können alle nötigen Informationen
herausgefunden werden, welche für die Erstellung eines UMLs relevant sind.
Das Javaparser Projekt ist gut dokumentiert und wird beispielsweise
von IntelliJ und Github verwendet.

• the JavaParser class provides a full API for producing an AST from code
• the StaticJavaParser class provides a quick and simple API for producing an AST from code.
• the CompilationUnit is the root of the AST
• the Visitors are classes which are used to find specific parts of the AST

https://tomassetti.me/getting-started-with-javaparser-analyzing-java-code-programmatically/
https://www.javacodegeeks.com/2017/12/javaparser-generate-analyze-modify-java-code.html

https://github.com/pratiksanglikar/Java-Parser-UML-Generator

https://javaconceptoftheday.com/list-all-files-in-directory-in-java/

== JavaSymbolSolver

Als Teil des Javaparser kann zudem javaSymbolSolver verwendet werden.
Dieser kann theretisch Herkunft der Methodenaufrufe und Variablendeklarationen bestimmen.
Dieses Projekt ist allerdings noch sehr neu und gemäss dem Auhtor wenig verbreitet und dokumentiert.
Die Verwendung der javaSymbolSolver API ist eher umsändlich.

//
https://stackoverflow.com/questions/3403909/get-generic-type-of-class-at-runtime

// Reflection API extended Guava
https://www.baeldung.com/guava-reflection

// Get Reference Type
https://stackoverflow.com/questions/2674554/how-do-you-know-a-variable-type-in-java
https://stackoverflow.com/questions/20987910/how-to-get-the-type-of-object-reference-of-instance