= Java to UML Parser

Dieses Dokument sammelt mögliche Lösungen um aus .java Files
UML darzustellen.

== Reflection

* Reflection is commonly used by programs which require the ability to examine or modify the runtime behavior
of applications running in the Java virtual machine.
https://docs.oracle.com/javase/tutorial/reflect/
https://www.javatpoint.com/java-reflection

* private fields and methods
http://tutorials.jenkov.com/java-reflection/private-fields-and-methods.html


== Java.lang.Class.getMethods() Method

* Nur public Methoden
https://www.tutorialspoint.com/java/lang/class_getmethods.htm


== Teilweise vorgefertigte Lösungen

* eher unflexibel, weil diverse Tools benötigt werden
https://github.com/rishirajrandive/uml-parser

* Favorit: einfach, mächtig und flexibel
https://github.com/javaparser/javaparser
https://github.com/javaparser/javaparser-maven-sample +
siehe Auch javaparservisited.pdf


* benutzt javaparser und yuml für uml visualisierung
https://github.com/shubhamvadhera/uml-parser

== Javaparser

Javaparser API kann .java Files parser und diese in einer
Baumartiger Struktur speichern. Dabei können alle nötigen Informationen
herausgefunden werden, welche für die Erstellung eines UMLs relevant sind.
Das Javaparser Projekt ist gut dokumentiert und wird beispielsweise
von IntelliJ und Github verwendet.

== JavaSymbolSolver

Als Teil des Javaparser kann zudem javaSymbolSolver verwendet werden.
Dieser kann theretisch Herkunft der Methodenaufrufe und Variablendeklarationen bestimmen.
Dieses Projekt ist allerdings noch sehr neu und gemäss dem Auhtor wenig verbreitet und dokumentiert.
Die Verwendung der javaSymbolSolver API ist eher umsändlich.