= Projektvereinbarung


*Autoren:* Dimitri Muralt, Christoph Wenk +
*Auftraggeber:* Dieter Holz, Barbara Scheuner +
*Betreuer:* Dieter Holz, Barbara Scheuner

== Einleitung

Dieses Dokument gilt als Vereinbarung zwischen den Auftraggebern Barbara Scheuner und Dieter Holz, die gleichzeitig auch die Funktion als Betreuungspersonen übernehmen, und dem Projektteam bestehend aus Christoph Wenk und Dimitri Muralt. Das Dokument enthält die Kontaktdaten sowie allgemeine Informationen über den Projektablauf und Umfang. Das Dokument muss von beiden Parteien akzeptiert werden  (via Pull Request mit allen Parteien als Reviewer auf Github) und legt fest, was bis zum Abschluss des Projektes fertiggestellt werden soll. Änderungen an diesem Dokument sind möglich, wenn sie von allen Seiten akzeptiert werden. Es ist erlaubt, die Änderungen per Pull Request mit allen Parteien als Reviewer auf Github mitzuteilen.

== Vorliegende Dokumente

Diese Vereinbarung basiert unter anderem auf dem Projektbeschrieb "IMVS21_inheritorGallery.pdf” sowie den Meetings vom 26. Februar 2019 und 19. März 2019.

== Ausgangslage

Das Klassendiagramm von UML stellt die Vererbungsbeziehungen zwischen Klassen und Interfaces dar. Dabei werden die Klassen mit ihren Attributen und Methoden als einzelne Quadrate gezeigt. Für die resultierenden Instanzen einer abgeleiteten Klasse ist diese Darstellung irreführend. Für das Verständnis was eine Instanz ausmacht wäre es für einen Programmieranfänger deutlich einfacher wenn die Instanz als eine Einheit visualisiert wird und nicht in mehreren Blöcken.

Eine für Programmieranfänger geeignete Visualisierung von Instanzen müsste:

- die verfügbaren Methoden und Attribute und deren Ursprungs-Klasse bzw. Interface nachvollziehbar machen
- den statischen und dynamischen Typ eines Attributs bzw. einer Variablen berücksichtigen

Ein Debugger bietet einige dieser Informationen an. Eine grafische Visualisierung existiert derzeit nicht.

== Ziel der Arbeit

Entwicklung einer interaktiven Lernumgebung für den Einsatz im Unterricht für Programmieranfänger auf Basis JavaFX.
Für den Programmieranfänger soll es möglich sein, typische Aufgabenstellungen und Programmier-Übungen im Bereich Vererbung und Polymorphie schrittweise zu implementieren und mit bestehenden Klassenhierarchien zu experimentieren. Die entstehenden Instanzen sollen geeignet graphisch visualisiert werden.

== Problemstellung

InheritorGallery besteht aus zwei Teilen

- Autorensystem mit dem neue Übungen erstellt werden (insbesondere Vererbungsstrukturen)
- Lernsystem mit dem der Programmieranfänger die Übungen durchführt

Für beide Teile

- Evaluation bestehender Ansätze und Lösungen
- Evaluation geeigneter Technologien
- Entwurf eines geeigneten User-Interfaces
- systematische Usability-Tests zur Weiterentwicklung der User-Interfaces

Für die Lernumgebung

- Entwurf der Visualisierung von Instanzen von Klassen mit mehreren Oberklassen und Interfaces
- dynamische Veränderung der Visualisierung je nach Programmzustand

== Rahmenbedingungen
In folgenden Abschnitten wird zwischen Dokumenten und Komponenten, die zu erstellen bzw. nicht zu erstellen sind, unterschieden.

=== In scope

.Deliverables
|===
|Deliverable | Inhalt

|Projektvereinbarung
a|
- Projektbeschreibung
- Rahmenbedingungen
- Funktionale- / Nicht-funktionale Anforderungen
- Projektplanung
- Freigabe & Genehmigung

|UX-Konzept
a|
- Usability-Tests
- Finaler Prototyp
- Personas

|Fachbericht
a|
- Schwerpunkt
- Vorgehen
- Analysen
- Architektur
- Technologien / Software
- Fazit

|===

=== Out of scope
- Admin GUI

== Anforderungen
===  Use Cases

.UseCases
|===
|# | Bezeichnung

|UC-1
|Übung importieren

|UC-2
|Objekte instanzieren

|UC-3
|Mit Objekten interagieren

|UC-4
|Klassen erstellen und bearbeiten

|===
=== Funktionale Anforderungen
.Funktionale Anforderungen
|===
|# | UC | Prio | Bezeichnung | Beschreibung

|tbd
|tbd
|tbd
|tbd
|tbd

|===

=== Nicht-funktionale Anforderungen

.Nichtfunktionale Anforderungen
|===
|# | Beschreibung

|NF-1
|Die Applikation soll mit Liberica JDK 11 lauffähig sein.

|NF-2
|Die Applikation muss von Java-Programmieranfängern zu bedienen sein.

|NF-3
|tbd

|NF-4
|tbd

|===






== Produkteinsatz
=== Anwendungsbereiche
=== Zielgruppe

== Projektplanung
=== Meetings


== Freigabe / Genehmigung

Mit dieser Projektvereinbarung werden die Ziele sowie die Rahmenbedingungen für das IP-5 Projekt “InheritorGallery“ festgehalten. Dieses Dokument dient als vertragliche Grundlage zwischen den vorgängig genannten Parteien.


Diese Vereinbarung wird aufgrund eines Pull Requests auf dem InheritorGallery GitHub-Repository https://github.com/FHNW-IP5-IP6/InheritorGallery auf den master-Branch mit allen Beteiligten als Reviewer akzeptiert.