name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Set up JDK 11.0
      uses: airsquared/setup-java@master
      with:
        java-version: '11.0.2'
        javafx: true
    - name: Build and test with Gradle
      run: ./gradlew build
